version: '3'

services:
  chat-server-app-api:
    build:
      context: ./chat-app-server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=mysql-db
      - DB_NAME=test
    networks:
      - my-network
    depends_on:
      - mysql-db
      - chat-server-app-websocket
  
  chat-server-app-websocket:
    build:
      context: ./chat-app-server  # Replace with the path to your WebSocket app
      dockerfile: Dockerfile
    ports:
      - "4006:4006"
    environment:
      - DB_HOST=mysql-db
      - DB_NAME=test
    networks:
      - my-network

  mysql-db:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: user1
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mysql_data:/var/lib/mysql
    # Consider adding the following line to connect to the default network:
    # networks:
    #   - default

volumes:
  mysql_data:
networks:
  my-network: